x-airflow-common: &airflow-common
  image: apache/airflow:2.10.2
  environment: &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "true"
    _PIP_ADDITIONAL_REQUIREMENTS: pandas pyarrow faker pyyaml matplotlib sqlalchemy psycopg2-binary confluent-kafka pyspark
    PYTHONPATH: /opt/airflow/project
  volumes:
    - ${AIRFLOW_PROJ_DIR:-./airflow}/dags:/opt/airflow/dags
    - ${AIRFLOW_PROJ_DIR:-./airflow}/logs:/opt/airflow/logs
    - ${AIRFLOW_PROJ_DIR:-./airflow}/plugins:/opt/airflow/plugins
    - ./:/opt/airflow/project
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    airflow-postgres:
      condition: service_healthy
      