FROM python:3.11-slim

WORKDIR /app

COPY . .

RUN pip install --no-cache-dir fastapi uvicorn pandas sqlalchemy psycopg2-binary pyarrow

CMD ["uvicorn", "src.api.main:app", "--host", "0.0.0.0", "--port", "8000"]
